# set clone depth
clone_depth: 1                  # clone entire repository history if not defined

environment:
  TEST_SUITE: test
  PACKAGES: "latest"
  SUITE: "test"
  GAP: "master"
  DIGRAPHS_LIB: "digraphs-lib-0.6"
  SETUP: "appveyor"

  # To test building GAP both using the bundled libraries (zlib and GMP), as
  # well as using the versions distributed with cygwin, we do the former in
  # the 32 bit build and the latter in the 64 bit build. But building zlib
  # does not see to work if '--coverage' is used, so we only use that flag in
  # the 64 bit build.
  matrix:
    #- CYG_ARCH: x86
    #  ABI: 32
    #  CYG_ROOT: C:\cygwin
    #  PKGS: "-P python27,python27-pip"
    #  PKG_FLAGS: "CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 LOPTS=-m32"
    - CYG_ARCH: x86_64
      ABI: 64
      CYG_ROOT: C:\cygwin64
      PKGS: "-P libgmp-devel,zlib-devel,python27,python27-pip"

## change to packages-stable-X.Y.tar.gz in the stable branch
#cache:
#  - packages-master.tar.gz

install:
  - '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l %CYG_ROOT%/var/cache/setup %PKGS%'

# scripts that run after cloning repository
build_script:
# If there's a newer build queued for the same PR, cancel this one
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - SET "PATH=%CYG_ROOT%\bin;%PATH%"
    # $HOME=pwd=/home/appveyor
    # $APPVEYOR_BUILD_FOLDER=C:\projects\digraphs
    # $APPVEYOR_BUILD_FOLDER=/cygdrive/c/projects/digraphs
    #- bash -lc "cd $APPVEYOR_BUILD_FOLDER && cd .. && export HOME=`pwd`"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./scripts/travis-build-dependencies.sh"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./scripts/travis-build-digraphs.sh"

test_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./scripts/travis-test.sh"
