dist:
  xenial

language:
  c

compiler:
  gcc

env:
  global:
    - DIGRAPHS_LIB=digraphs-lib-0.5

#   GAP version: |       master | stable-4.10 | stable-4.9 |     required |
# ---------------+--------------+-------------+------------+--------------+
# pkgs:   latest | 64- & 32-bit |      32-bit |          - |            - |
# pkgs: required |  coverage-64 |      64-bit |     64-bit | 64- & 32-bit |

matrix:
  include:
    - env:
      - SUITE=lint

    - env:
      - SUITE=test
      - ABI=64
      - GAP=master
      - PACKAGES=latest

    - env:
      - SUITE=test
      - ABI=32
      - GAP=master
      - PACKAGES=latest
      addons:
        apt_packages:
          - g++-multilib

    - env:
      - SUITE=test
      - ABI=32
      - GAP=stable-4.10
      - PACKAGES=latest
      addons:
        apt_packages:
          - g++-multilib

    - env:
      - SUITE=test
      - ABI=64
      - GAP=stable-4.10
      - PACKAGES=required

    - env:
      - SUITE=test
      - ABI=64
      - GAP=stable-4.9
      - PACKAGES=required

    - env:
      - SUITE=test
      - ABI=64
      - GAP=required
      - PACKAGES=required

    - env:
      - SUITE=test
      - ABI=32
      - GAP=required
      - PACKAGES=required
      addons:
        apt_packages:
          - g++-multilib

    - env:
      - SUITE=coverage
      - ABI=64
      - GAP=master
      - PACKAGES=required
      - THRESHOLD=98

install:
  # GAP and some packages require special flags for compilation in 32-bit mode
  - if [ "$ABI" == "32" ]; then
      export GAP_FLAGS="ABI=32 --host=i686-linux-gnu";
      export PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 LOPTS=-m32 --host=i686-linux-gnu";
    fi;

before_script:
  - export GAPROOT="$HOME/gap"
  - scripts/travis-build-dependencies.sh

script:
  - scripts/travis-build-digraphs.sh && scripts/travis-test.sh
