name: Config-options
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - stable-*.*
  schedule:
    # Every day at 3:30 AM UTC
    - cron: 30 3 * * *
env:
  NO_COVERAGE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  with-external-planarity-bliss:
    name: ${{ matrix.bliss }} ${{ matrix.planarity }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        planarity:
          - --with-external-planarity
          - ""
        bliss:
          - --with-external-bliss
          - ""
        exclude:
          - planarity: ""
            bliss: ""
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v5
      - name: Output g++ version . . .
        run: g++ --version
      - name: Install micromamba environment from environment.yml . . .
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: digraphs
          cache-environment: true
          create-args: ${{ matrix.bliss && 'bliss' || '' }} ${{ matrix.planarity && 'planarity' || ''}}
      - name: Set environment variables . . .
        run: |
          echo "PKG_CONFIG_PATH=$MAMBA_ROOT_PREFIX/envs/digraphs/lib/pkgconfig:$MAMBA_ROOT_PREFIX/envs/digraphs/share/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$MAMBA_ROOT_PREFIX/envs/digraphs/lib" >> $GITHUB_ENV
          echo "CFLAGS=-I$MAMBA_ROOT_PREFIX/envs/digraphs/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L$MAMBA_ROOT_PREFIX/envs/digraphs/lib" >> $GITHUB_ENV
      - name: Install GAP and clone/compile necessary packages . . .
        uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_CLONE: NautyTracesInterface digraphs/graphviz
          GAP_PKGS_TO_BUILD: io orb datastructures grape NautyTracesInterface
          GAPBRANCH: stable-4.14
      - name: Build Digraphs . . .
        uses: gap-actions/build-pkg@v1
        with:
          CONFIGFLAGS: ${{ matrix.bliss }} ${{ matrix.planarity }}
      - name: Run Digraphs package's tst/teststandard.g . . .
        uses: gap-actions/run-pkg-tests@v3
        with:
          NO_COVERAGE: true

  all-options:
    name: ${{ matrix.debug }} ${{ matrix.warnings }} ${{ matrix.without-intrinsics }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        warnings:
          - "--enable-compile-warnings"
          - ""
        debug:
          - "--enable-debug"
          - ""
        without-intrinsics:
          - "--without-intrinsics"
          - ""
        exclude:
          - warnings: ""
            debug: ""
            without-intrinsics: ""

    steps:
      - uses: actions/checkout@v5
      - name: Output g++ version . . .
        run: g++ --version
      - name: Install GAP and clone/compile necessary packages . . .
        uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_CLONE: NautyTracesInterface digraphs/graphviz
          GAP_PKGS_TO_BUILD: io orb datastructures grape NautyTracesInterface
          GAPBRANCH: stable-4.14
      - name: Build Digraphs . . .
        uses: gap-actions/build-pkg@v1
        with:
          CONFIGFLAGS: ${{ matrix.debug }} ${{ matrix.without-intrinsics }} ${{ matrix.warnings && '--enable-compile-warnings WARNING_CXXFLAGS="-Werror" WARNING_CFLAGS="-Werror"' || '' }}
      - name: Run Digraphs package's tst/teststandard.g . . .
        uses: gap-actions/run-pkg-tests@v3
