name: Valgrind
on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    paths:
      - src/*.[hc]
  pull_request:
    paths:
      - src/*.[hc]

env:
  VALGRIND: valgrind --trace-children=yes --leak-check=full --error-exitcode=1
  NO_COVERAGE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-valgrind:
    name: Ubuntu / GAP stable-4.14 / valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Output g++ version . . .
        run: g++ --version
      - name: Install Valgrind . . .
        run: sudo apt-get install valgrind
      - name: Install GAP and clone/compile necessary packages . . .
        uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_CLONE: NautyTracesInterface digraphs/graphviz
          GAP_PKGS_TO_BUILD: io orb datastructures grape NautyTracesInterface
          GAPBRANCH: stable-4.14
          CONFIGFLAGS: --enable-valgrind
      - name: Build Digraphs . . .
        uses: gap-actions/build-pkg@v1
      - name: Run DigraphsTestInstall . . .
        uses: gap-actions/run-pkg-tests@v3
        with:
          NO_COVERAGE: true
          GAP_TESTFILE: tst/github_actions/install.g
          pre-gap: ${{ env.VALGRIND }}
      - name: Run DigraphsTestStandard . . .
        uses: gap-actions/run-pkg-tests@v3
        with:
          NO_COVERAGE: true
          GAP_TESTFILE: tst/github_actions/standard.g
          pre-gap: ${{ env.VALGRIND }}
